import { DiagnosticQuestion, Phase, DailySchedule, Achievement, WritingProject } from "./types";

export const diagnosticQuestions: DiagnosticQuestion[] = [
  // Part A: Phonetic Awareness (Questions 1-8)
  { id: 1, part: "A", type: "spelling", question: "Spell this word: beautiful", correctAnswer: "beautiful", points: 1, category: "phonetic" },
  { id: 2, part: "A", type: "spelling", question: "Spell this word: receive", correctAnswer: "receive", points: 1, category: "phonetic" },
  { id: 3, part: "A", type: "spelling", question: "Spell this word: separate", correctAnswer: "separate", points: 1, category: "phonetic" },
  { id: 4, part: "A", type: "spelling", question: "Spell this word: believe", correctAnswer: "believe", points: 1, category: "phonetic" },
  { id: 5, part: "A", type: "spelling", question: "Spell this word: beginning", correctAnswer: "beginning", points: 1, category: "phonetic" },
  { id: 6, part: "A", type: "fill_blank", question: "Add '-ed' to 'play'", correctAnswer: "played", points: 2, category: "morphophonemic" },
  { id: 7, part: "A", type: "fill_blank", question: "Add '-ed' to 'cry'", correctAnswer: "cried", points: 2, category: "morphophonemic" },
  { id: 8, part: "A", type: "spelling", question: "Spell this sports word: tournament", correctAnswer: "tournament", points: 2, category: "vocabulary" },
  // Part B: Spelling Rules Knowledge
  { id: 9, part: "B", type: "fill_blank", question: "What happens when you add '-ing' to 'make'?", correctAnswer: "making", points: 2, category: "rules" },
  { id: 10, part: "B", type: "fill_blank", question: "I before E except after ___ (fill in the letter)", correctAnswer: ["c", "C"], points: 2, category: "rules" },
  { id: 11, part: "B", type: "multiple_choice", question: "Choose the correct spelling:", options: ["accross", "across"], correctAnswer: "across", points: 2, category: "rules" },
  { id: 12, part: "B", type: "multiple_choice", question: "Choose the correct spelling:", options: ["occured", "occurred"], correctAnswer: "occurred", points: 2, category: "rules" },
  { id: 13, part: "B", type: "multiple_choice", question: "Choose the correct spelling:", options: ["untill", "until"], correctAnswer: "until", points: 2, category: "rules" },
  { id: 14, part: "B", type: "multiple_choice", question: "Choose the correct spelling:", options: ["tommorow", "tomorrow"], correctAnswer: "tomorrow", points: 2, category: "rules" },
  { id: 15, part: "B", type: "fill_blank", question: "Form the plural of 'tooth'", correctAnswer: "teeth", points: 2, category: "plurals" },
  { id: 16, part: "B", type: "fill_blank", question: "Form the plural of 'crisis'", correctAnswer: "crises", points: 2, category: "plurals" },
  // Part C: Context and Application
  { id: 17, part: "C", type: "multiple_choice", question: "'She gave me a nice ___' (kind words)", options: ["compliment", "complement"], correctAnswer: "compliment", points: 2, category: "homophones" },
  { id: 18, part: "C", type: "multiple_choice", question: "'The colors ___ each other' (go well together)", options: ["compliment", "complement"], correctAnswer: "complement", points: 2, category: "homophones" },
  { id: 19, part: "C", type: "spelling", question: "Spell this word correctly: charactor (character in a story)", correctAnswer: "character", points: 2, category: "vocabulary" },
  { id: 20, part: "C", type: "spelling", question: "Spell this word correctly: favorit (something you like best)", correctAnswer: "favorite", points: 2, category: "vocabulary" },
  { id: 21, part: "C", type: "spelling", question: "Spell this word correctly: achived (reached a goal)", correctAnswer: "achieved", points: 2, category: "vocabulary" },
  { id: 22, part: "C", type: "spelling", question: "Spell this word correctly: oponent (someone you compete against)", correctAnswer: "opponent", points: 2, category: "vocabulary" },
  // Part D: Creative Writing Vocabulary
  { id: 23, part: "D", type: "spelling", question: "Spell this literary term: protagonist (main character)", correctAnswer: "protagonist", points: 2, category: "literary" },
  { id: 24, part: "D", type: "spelling", question: "Spell this descriptive word: mysterious", correctAnswer: "mysterious", points: 2, category: "descriptive" },
  { id: 25, part: "D", type: "spelling", question: "Spell this descriptive word: courageous", correctAnswer: "courageous", points: 2, category: "descriptive" }
];

export const phases: Phase[] = [
  {
    phaseNumber: 1,
    title: "Phonics Foundation Review",
    description: "Master sound-symbol correspondence and basic syllable types",
    objectives: [
      "Master sound-symbol correspondence for all 44 phonemes",
      "Accurately decode and encode single-syllable and simple multisyllabic words",
      "Identify and apply basic syllable types (closed, open, vowel-consonant-e, r-controlled)",
      "Recognize and spell common consonant blends and digraphs"
    ],
    keyConcepts: [
      "Short and long vowel sounds in context",
      "Consonant blends (bl-, str-, -nd, -nch)",
      "Consonant digraphs (sh, ch, th, ph, wh)",
      "R-controlled vowels (ar, er, ir, or, ur)",
      "Syllable division patterns (VC/CV, V/CV, VC/V)",
      "Basic prefixes (un-, re-, pre-) and suffixes (-s, -es, -ing, -ed)"
    ],
    milestones: [
      { week: 1, milestone: "Accurately spell 90% of CVC words" },
      { week: 2, milestone: "Master consonant blends and digraphs with 85% accuracy" },
      { week: 3, milestone: "Correctly divide and spell 80% of two-syllable words" },
      { week: 4, milestone: "Apply basic prefixes/suffixes with 85% accuracy" }
    ],
    totalSessions: 20,
    weeks: "Weeks 1-4"
  },
  {
    phaseNumber: 2,
    title: "Common Spelling Patterns",
    description: "Master common spelling patterns and word families",
    objectives: [
      "Master common spelling patterns and word families",
      "Apply spelling rules for adding suffixes",
      "Recognize and spell words with common prefixes",
      "Distinguish between similar-sounding spelling patterns"
    ],
    keyConcepts: [
      "Drop-e rule (take → taking, hope → hoping)",
      "Doubling rule (run → running, big → bigger)",
      "Change-y-to-i rule (try → tried, happy → happiest)",
      "Plural formation rules (regular, -es, -ies, irregular)",
      "Common word families (-ight, -ought, -ough, -tion, -sion)",
      "Prefixes: dis-, mis-, non-, over-, sub-, inter-"
    ],
    milestones: [
      { week: 5, milestone: "Apply drop-e rule with 90% accuracy" },
      { week: 6, milestone: "Apply doubling rule with 85% accuracy" },
      { week: 8, milestone: "Master y-to-i rule and plural formations with 80% accuracy" },
      { week: 10, milestone: "Correctly use learned prefixes/suffixes in creative writing" }
    ],
    totalSessions: 30,
    weeks: "Weeks 5-10"
  },
  {
    phaseNumber: 3,
    title: "Irregular Words & Exceptions",
    description: "Master high-frequency irregular words and silent letters",
    objectives: [
      "Master high-frequency irregular words (demon words)",
      "Recognize and spell words with silent letters",
      "Understand etymology-based spelling (foreign borrowings)",
      "Apply 'I before E' rule and its exceptions"
    ],
    keyConcepts: [
      "Silent letters: k (knife), w (write), g (gnaw), b (thumb)",
      "Irregular high-frequency words: colonel, necessary, rhythm, Wednesday",
      "Foreign borrowings: ballet, café, karate, tsunami",
      "I before E rule: receive, believe, ceiling, weird",
      "Assimilated prefixes: ad- (accomplish), in- (illegal)"
    ],
    milestones: [
      { week: 12, milestone: "Master 20 high-frequency irregular words" },
      { week: 13, milestone: "Spell words with silent letters at 80% accuracy" },
      { week: 14, milestone: "Apply I before E rule and exceptions with 85% accuracy" },
      { week: 16, milestone: "Use 15+ irregular words correctly in creative writing" }
    ],
    totalSessions: 30,
    weeks: "Weeks 11-16"
  },
  {
    phaseNumber: 4,
    title: "Homophones & Confusing Words",
    description: "Distinguish between common homophones through context",
    objectives: [
      "Distinguish between common homophones through context",
      "Master commonly confused word pairs",
      "Apply appropriate word choice in writing",
      "Understand semantic differences between similar-sounding words"
    ],
    keyConcepts: [
      "Common homophones: their/there/they're, your/you're, to/too/two, its/it's",
      "6th-grade homophones: compliment/complement, capitol/capital, principal/principle",
      "Confusing word pairs: accept/except, desert/dessert, loose/lose",
      "Context-dependent spelling: lead vs. led, read vs. read"
    ],
    milestones: [
      { week: 18, milestone: "Master 10 most common homophone pairs with 90% accuracy" },
      { week: 19, milestone: "Apply grade-level homophones correctly in sentences" },
      { week: 20, milestone: "Use confusing word pairs correctly in original writing" },
      { week: 21, milestone: "Demonstrate mastery through error-free paragraph writing" }
    ],
    totalSessions: 25,
    weeks: "Weeks 17-21"
  },
  {
    phaseNumber: 5,
    title: "Advanced Vocabulary & Academic Words",
    description: "Master Greek and Latin roots for vocabulary expansion",
    objectives: [
      "Master Greek and Latin roots for vocabulary expansion",
      "Spell complex academic and content-area vocabulary",
      "Apply morphological analysis to unknown words",
      "Build creative writing vocabulary with sophisticated word choice"
    ],
    keyConcepts: [
      "Greek roots: tele- (telephone), photo- (photograph), bio- (biography)",
      "Latin roots: script (manuscript), dict (dictionary), port (transport)",
      "Academic vocabulary: analysis, evaluate, synthesize, hypothesis",
      "Content-area words: ecosystem, democracy, equation, metaphor"
    ],
    milestones: [
      { week: 22, milestone: "Identify and define 15 Greek/Latin roots" },
      { week: 23, milestone: "Use morphological analysis to spell 80% of unfamiliar words" },
      { week: 25, milestone: "Master 30 academic vocabulary words" },
      { week: 26, milestone: "Incorporate 20+ advanced words in creative writing" }
    ],
    totalSessions: 25,
    weeks: "Weeks 22-26"
  },
  {
    phaseNumber: 6,
    title: "Creative Writing Mastery",
    description: "Apply all learned spelling skills in creative writing contexts",
    objectives: [
      "Apply all learned spelling skills in creative writing contexts",
      "Master specialized vocabulary for creative writing",
      "Self-edit and proofread for spelling accuracy",
      "Create polished, publication-ready creative pieces"
    ],
    keyConcepts: [
      "Literary terminology: protagonist, antagonist, exposition, foreshadowing",
      "Descriptive vocabulary: luminous, melodious, velvety, exasperated",
      "Dialogue tags: exclaimed, murmured, interrupted, hesitated",
      "Genre-specific vocabulary: fantasy, mystery, sci-fi"
    ],
    milestones: [
      { week: 27, milestone: "Master 25 literary terms with correct spelling" },
      { week: 28, milestone: "Create a 500-word piece with 95%+ spelling accuracy" },
      { week: 29, milestone: "Demonstrate effective self-editing process" },
      { week: 30, milestone: "Complete portfolio with 3+ polished pieces" }
    ],
    totalSessions: 20,
    weeks: "Weeks 27-30"
  }
];

export const getDailySchedule = (phase: number, dayOfWeek: string): DailySchedule => {
  const schedules: Record<number, Record<string, DailySchedule>> = {
    1: {
      monday: {
        dayOfWeek: "Monday",
        visual: { title: "Phoneme-Grapheme Mapping", description: "Review flashcards showing sound-symbol correspondences. Color-code syllable types in 5 multisyllabic words.", duration: 10 },
        auditory: { title: "Sound Blending & Segmentation", description: "Practice blending sounds aloud using 10 target words. Phoneme segmentation: say each sound while tapping.", duration: 10 },
        kinesthetic: { title: "Multi-Sensory Reinforcement", description: "Skywriting: Write 5 challenging words in air with large arm movements while spelling aloud.", duration: 10 }
      },
      tuesday: {
        dayOfWeek: "Tuesday",
        visual: { title: "Word Families & Pattern Recognition", description: "Create word family chart (e.g., -ight family). Identify common patterns in themed word list.", duration: 10 },
        auditory: { title: "Dictation & Listening", description: "Listen to 8 words from weekly list and write them. Read words aloud for self-checking.", duration: 10 },
        kinesthetic: { title: "Active Learning", description: "Letter tile building: Use manipulatives to build 6 target words. Online phonics game.", duration: 10 }
      },
      wednesday: {
        dayOfWeek: "Wednesday",
        visual: { title: "Phoneme-Grapheme Mapping", description: "Review flashcards showing sound-symbol correspondences. Color-code syllable types in 5 multisyllabic words.", duration: 10 },
        auditory: { title: "Sound Blending & Segmentation", description: "Practice blending sounds aloud using 10 target words. Say-spell-say practice.", duration: 10 },
        kinesthetic: { title: "Multi-Sensory Reinforcement", description: "Sand/shaving cream tracing: Trace letters while saying sounds. Sports Spelling Race.", duration: 10 }
      },
      thursday: {
        dayOfWeek: "Thursday",
        visual: { title: "Word Families & Pattern Recognition", description: "Create word family chart (e.g., -ight family). Identify common patterns in themed word list.", duration: 10 },
        auditory: { title: "Dictation & Listening", description: "Create a silly sentence using 4 target words; say aloud dramatically.", duration: 10 },
        kinesthetic: { title: "Active Learning", description: "Movement spelling: Jump rope or bounce ball for each letter. Online game session.", duration: 10 }
      },
      friday: {
        dayOfWeek: "Friday",
        visual: { title: "Phoneme-Grapheme Mapping", description: "Weekly review of sound-symbol correspondences. Color-code syllable types.", duration: 10 },
        auditory: { title: "Sound Blending & Segmentation", description: "Final practice of weekly words. Say-spell-say method.", duration: 10 },
        kinesthetic: { title: "Multi-Sensory Reinforcement", description: "Skywriting and spelling race. Review all weekly words with movement.", duration: 10 }
      }
    }
  };
  
  // Default schedule structure for other phases
  const defaultSchedule: DailySchedule = {
    dayOfWeek: dayOfWeek.charAt(0).toUpperCase() + dayOfWeek.slice(1),
    visual: { title: "Visual Learning", description: "Pattern recognition, flashcards, and color-coded word study.", duration: 10 },
    auditory: { title: "Auditory Learning", description: "Dictation, oral spelling practice, and listening exercises.", duration: 10 },
    kinesthetic: { title: "Kinesthetic Learning", description: "Movement-based activities, games, and hands-on practice.", duration: 10 }
  };
  
  return schedules?.[phase]?.[dayOfWeek.toLowerCase()] ?? defaultSchedule;
};

export const achievements: Achievement[] = [
  { id: "first_session", title: "Getting Started", description: "Complete your first study session", iconName: "Rocket", category: "milestones", requirement: "Complete 1 session", threshold: 1 },
  { id: "week_streak_3", title: "Hot Streak", description: "Study 3 days in a row", iconName: "Flame", category: "streaks", requirement: "3 day streak", threshold: 3 },
  { id: "week_streak_7", title: "On Fire!", description: "Study 7 days in a row", iconName: "Fire", category: "streaks", requirement: "7 day streak", threshold: 7 },
  { id: "words_25", title: "Word Collector", description: "Master 25 words", iconName: "BookOpen", category: "vocabulary", requirement: "Master 25 words", threshold: 25 },
  { id: "words_50", title: "Vocabulary Builder", description: "Master 50 words", iconName: "Library", category: "vocabulary", requirement: "Master 50 words", threshold: 50 },
  { id: "words_100", title: "Word Wizard", description: "Master 100 words", iconName: "Wand2", category: "vocabulary", requirement: "Master 100 words", threshold: 100 },
  { id: "phase_1_complete", title: "Foundation Master", description: "Complete Phase 1", iconName: "Medal", category: "phases", requirement: "Complete Phase 1", threshold: 1 },
  { id: "phase_2_complete", title: "Pattern Pro", description: "Complete Phase 2", iconName: "Puzzle", category: "phases", requirement: "Complete Phase 2", threshold: 1 },
  { id: "phase_3_complete", title: "Exception Expert", description: "Complete Phase 3", iconName: "Sparkles", category: "phases", requirement: "Complete Phase 3", threshold: 1 },
  { id: "perfect_score", title: "Perfect!", description: "Get 100% on any exercise", iconName: "Star", category: "accuracy", requirement: "100% accuracy", threshold: 1 },
  { id: "writing_project_1", title: "Creative Writer", description: "Complete your first writing project", iconName: "Pencil", category: "writing", requirement: "Complete 1 project", threshold: 1 },
  { id: "writing_project_5", title: "Author in Training", description: "Complete 5 writing projects", iconName: "BookText", category: "writing", requirement: "Complete 5 projects", threshold: 5 },
  { id: "diagnostic_complete", title: "Diagnosed!", description: "Complete the diagnostic assessment", iconName: "ClipboardCheck", category: "milestones", requirement: "Complete diagnostic", threshold: 1 },
  { id: "accuracy_90", title: "Sharp Speller", description: "Achieve 90% overall accuracy", iconName: "Target", category: "accuracy", requirement: "90% accuracy", threshold: 90 },
  { id: "hours_10", title: "Dedicated Learner", description: "Study for 10 hours total", iconName: "Clock", category: "time", requirement: "10 hours", threshold: 600 }
];

export const writingProjects: WritingProject[] = [
  { id: "1", projectNumber: 1, title: "Sports Trading Cards Collection", objective: "Create trading cards for favorite athletes with accurate spelling of names, teams, and statistics.", materials: "Index cards, markers, sports magazines", instructions: ["Choose 10 athletes from different sports", "Create trading card with: Name, team, position, 3 stats, 1 fun fact", "Focus on spelling: position names, action verbs"], spellingFocus: "Proper nouns, sports vocabulary, past tense verbs", time: "30 minutes", phase: "1-2", level: "Beginner" },
  { id: "2", projectNumber: 2, title: "Game Controls Instruction Manual", objective: "Write an instruction manual for a favorite video game with accurate spelling.", materials: "Notebook, pencils, optional computer", instructions: ["List all game controls", "Write step-by-step instructions for basic gameplay", "Include 5 tips for beginners"], spellingFocus: "Command verbs, gaming vocabulary", time: "30-40 minutes", phase: "1-2", level: "Beginner" },
  { id: "3", projectNumber: 3, title: "Anime Character Name Tag Design", objective: "Create name tags for 8 anime characters with character traits.", materials: "Construction paper, markers, stickers", instructions: ["Choose 8 characters from different anime", "Design name tag with: Name, 3 personality traits, 1 special ability", "Decorate with symbols"], spellingFocus: "Adjectives, character trait vocabulary", time: "25-30 minutes", phase: "1-2", level: "Beginner" },
  { id: "4", projectNumber: 4, title: "Cartoon Episode Summary", objective: "Write plot summaries for 5 favorite cartoon episodes.", materials: "Notebook, episode references", instructions: ["Watch or recall 5 cartoon episodes", "Write 4-5 sentence summary for each", "Include: Beginning, middle, end, main problem, solution"], spellingFocus: "Sequence words, action verbs, plot vocabulary", time: "35-40 minutes", phase: "2", level: "Beginner" },
  { id: "5", projectNumber: 5, title: "Sports Play-by-Play Commentary", objective: "Write a sports commentary for a real or imagined game.", materials: "Paper, sports video optional", instructions: ["Choose a sport and game situation", "Write 10-15 sentences of play-by-play action", "Include player names, actions, exciting moments"], spellingFocus: "Present tense verbs, sports terminology, transition words", time: "30 minutes", phase: "2", level: "Beginner" },
  { id: "6", projectNumber: 6, title: "Video Game Review Blog", objective: "Write a 250-word game review with correct spelling and homophone usage.", materials: "Computer/notebook, game experience", instructions: ["Choose a recently played game", "Include: Title, genre, platform, ratings for graphics, gameplay, story", "Write pros and cons (3 each)", "Use at least 5 descriptive adjectives"], spellingFocus: "Homophones, descriptive vocabulary, irregular words", time: "45 minutes", phase: "3-4", level: "Intermediate" },
  { id: "7", projectNumber: 7, title: "Anime Character Profile Database", objective: "Create detailed profiles for 6 anime characters.", materials: "Notebook or digital document", instructions: ["Select 6 characters from different anime", "Create profile with: Full name, age, appearance, personality traits, abilities", "Focus on varied, sophisticated vocabulary"], spellingFocus: "Descriptive adjectives, irregular plurals, foreign borrowings", time: "50-60 minutes", phase: "3-4", level: "Intermediate" },
  { id: "8", projectNumber: 8, title: "Sports Hall of Fame Induction Speech", objective: "Write a 200-word induction speech for a favorite athlete.", materials: "Paper, athlete research", instructions: ["Research athlete's career achievements", "Write speech including: Introduction, 3 major accomplishments, character qualities", "Practice delivering speech aloud"], spellingFocus: "Silent letters, irregular words, formal vocabulary", time: "40 minutes", phase: "3-4", level: "Intermediate" },
  { id: "9", projectNumber: 9, title: "Game Strategy Guide", objective: "Create a comprehensive strategy guide for a favorite game.", materials: "Notebook, game knowledge", instructions: ["Choose one game level or challenge", "Write: Overview, objectives, step-by-step walkthrough", "Include tips & tricks, common mistakes to avoid"], spellingFocus: "Command forms, sequence words, gaming vocabulary", time: "50 minutes", phase: "3-4", level: "Intermediate" },
  { id: "10", projectNumber: 10, title: "Cartoon Crossover Story", objective: "Write a creative 300-word story featuring characters from 2 different cartoons.", materials: "Paper or computer", instructions: ["Choose 2 characters from different cartoons", "Create scenario where they meet", "Include dialogue (at least 6 exchanges)"], spellingFocus: "Homophones, dialogue punctuation, creative vocabulary", time: "45-50 minutes", phase: "4", level: "Intermediate" },
  { id: "11", projectNumber: 11, title: "E-Sports Tournament Report", objective: "Write a journalistic report on a real or fictional e-sports tournament.", materials: "Computer, tournament knowledge", instructions: ["Research or imagine an e-sports tournament", "Write 300-word report with key players, highlights, results", "Use academic vocabulary"], spellingFocus: "Academic words, gaming terminology, Greek/Latin roots", time: "60 minutes", phase: "5", level: "Advanced" },
  { id: "12", projectNumber: 12, title: "Anime Series Analysis Essay", objective: "Write a 400-word analytical essay about themes in a favorite anime.", materials: "Computer, anime knowledge", instructions: ["Choose an anime series", "Identify main theme", "Write essay with thesis, body paragraphs, conclusion"], spellingFocus: "Literary terms, academic vocabulary, complex words", time: "60-70 minutes", phase: "5-6", level: "Advanced" },
  { id: "13", projectNumber: 13, title: "Sports Science Article", objective: "Write an educational article explaining the science behind a sport.", materials: "Computer, research sources", instructions: ["Choose a sport", "Research scientific concepts", "Write 350-word accessible explanation"], spellingFocus: "Scientific vocabulary, academic terms, Greek/Latin roots", time: "70 minutes", phase: "5", level: "Advanced" },
  { id: "14", projectNumber: 14, title: "Original Game Design Document", objective: "Create a comprehensive design document for an original video game concept.", materials: "Computer or notebook", instructions: ["Design original game concept", "Include: Title, genre, story, characters, mechanics", "Use professional vocabulary"], spellingFocus: "Technical vocabulary, creative descriptive words", time: "80-90 minutes", phase: "5-6", level: "Advanced" },
  { id: "15", projectNumber: 15, title: "Anime Episode Script", objective: "Write a complete script for an original 5-minute anime episode.", materials: "Computer, script format reference", instructions: ["Create original characters", "Write script with scene descriptions, dialogue, sound cues", "Include literary elements"], spellingFocus: "Literary terms, dialogue tags, descriptive language", time: "90 minutes", phase: "6", level: "Advanced" },
  { id: "16", projectNumber: 16, title: "Sports Commentary Podcast Script", objective: "Write a 500-word podcast script analyzing a famous sports moment.", materials: "Computer, sports history research", instructions: ["Choose iconic sports moment", "Write with historical context, vivid details, analysis"], spellingFocus: "Advanced descriptive vocabulary, Greek/Latin roots", time: "60-70 minutes", phase: "6", level: "Advanced" },
  { id: "17", projectNumber: 17, title: "Game Review Comparison Article", objective: "Write a comparative analysis of 3 games in the same genre.", materials: "Computer, game experience", instructions: ["Choose 3 games from same genre", "Create comparison chart", "Write 500-word analysis"], spellingFocus: "Comparative language, technical vocabulary", time: "70-80 minutes", phase: "6", level: "Advanced" },
  { id: "18", projectNumber: 18, title: "Cartoon Animation Storyboard", objective: "Create a storyboard with detailed written descriptions for a short cartoon.", materials: "Large paper, drawing supplies", instructions: ["Plan 2-minute cartoon short", "Draw 8-10 panels with descriptions"], spellingFocus: "Cinematic vocabulary, action verbs, descriptive language", time: "90 minutes", phase: "6", level: "Advanced" },
  { id: "19", projectNumber: 19, title: "Fantasy Sports Team Report", objective: "Write a professional report analyzing fantasy sports team performance.", materials: "Computer, fantasy sports knowledge", instructions: ["Create or use existing fantasy team", "Write 400-word analysis"], spellingFocus: "Statistical vocabulary, analytical terms", time: "60 minutes", phase: "5-6", level: "Advanced" },
  { id: "20", projectNumber: 20, title: "My Gaming Journey", objective: "Create a comprehensive multimedia presentation about personal gaming history.", materials: "Computer, photos/screenshots", instructions: ["Outline personal gaming history", "Write 600-word narrative essay", "Add images with captions"], spellingFocus: "Narrative vocabulary, reflective language, literary devices", time: "120 minutes", phase: "6", level: "Advanced" }
];

export const spellingWords = {
  phase1: [
    // Original words
    "sprint", "strength", "splash", "shrink", "prompt", "twelfth", "sketch", "flake", "drone", "shrine",
    "basket", "picnic", "robot", "compete", "respond", "burger", "squirrel", "explore", "emergency", "territory",
    // Consonant blends
    "blanket", "branch", "bridge", "brother", "cluster", "crunch", "dragon", "dress", "flight", "freeze",
    "friend", "glitter", "grass", "grandpa", "planet", "practice", "present", "problem", "program", "promise",
    "scratch", "screen", "script", "scream", "string", "stripe", "strong", "street", "stretch", "straight",
    "thread", "throat", "throne", "through", "thrust", "traffic", "travel", "treasure", "tremble", "triangle",
    // Short vowels and digraphs
    "kitchen", "chicken", "chapter", "children", "champion", "challenge", "shadow", "shelter", "whisper", "whether",
    "phantom", "photograph", "elephant", "dolphin", "trophy", "alphabet", "nephew", "orphan", "triumph", "sphere",
    // R-controlled vowels
    "carpet", "harvest", "market", "target", "garden", "partner", "perfect", "perhaps", "perform", "permit",
    "nervous", "service", "certain", "curtain", "surface", "purpose", "surprise", "turnip", "turkey", "turtle"
  ],
  phase2: [
    // Original words
    "making", "hoping", "creating", "usable", "running", "biggest", "occurred", "traveler", "tried", "happiness",
    "beautiful", "studied", "foxes", "babies", "churches", "leaves", "heroes", "reefs", "shelves", "mice",
    "disagreement", "uncomfortable", "nonexistent", "overreaction", "subtraction", "intercontinental", "meaningful", "fearlessly", "hopelessness",
    // Drop-e rule
    "having", "giving", "taking", "coming", "loving", "moving", "proving", "serving", "shaking", "skating",
    "trading", "waving", "baking", "caring", "daring", "facing", "gracing", "placing", "racing", "spacing",
    // Doubling rule
    "batting", "cutting", "getting", "hitting", "letting", "putting", "setting", "sitting", "stopping", "swimming",
    "beginning", "forgetting", "occurring", "planning", "preferring", "referring", "regretting", "submitting", "winning", "wrapping",
    // Y to I rule
    "carried", "copied", "cried", "dried", "emptied", "fried", "hurried", "married", "replied", "worried",
    "busiest", "earliest", "easiest", "funniest", "happiest", "heaviest", "laziest", "luckiest", "prettiest", "ugliest",
    // Plurals
    "calves", "halves", "knives", "lives", "loaves", "scarves", "thieves", "wives", "wolves", "yourselves",
    "potatoes", "tomatoes", "echoes", "mosquitoes", "tornadoes", "volcanoes", "buffaloes", "dominoes", "mangoes", "zeroes"
  ],
  phase3: [
    // Original words
    "knowledge", "wrestle", "gnome", "psychology", "solemn", "salmon", "receipt", "scissors", "mortgage", "handsome",
    "necessary", "recommend", "occasion", "restaurant", "accommodate", "calendar", "colonel", "rhythm", "Wednesday", "Arctic",
    "receive", "believe", "weird", "neighbor", "ceiling", "achieve", "seizure", "freight",
    // Silent letters
    "knight", "knuckle", "knife", "knock", "knot", "kneel", "written", "wrapper", "wrinkle", "wrist",
    "gnarled", "gnaw", "design", "resign", "campaign", "foreign", "reign", "sovereign", "assign", "consign",
    "doubt", "debt", "subtle", "plumber", "thumb", "climb", "comb", "crumb", "dumb", "lamb",
    "aisle", "island", "isle", "debris", "chassis", "corps", "depot", "rapport", "rendezvous", "ballet",
    // I before E
    "achieve", "belief", "brief", "chief", "field", "grief", "piece", "relief", "shield", "thief",
    "yield", "fierce", "pierce", "frontier", "efficient", "sufficient", "ancient", "patient", "science", "conscience",
    // Exceptions and tricky words
    "absence", "abundance", "acquaintance", "appearance", "assistance", "attendance", "excellence", "existence", "independence", "intelligence",
    "maintenance", "performance", "perseverance", "preference", "presence", "reference", "resistance", "significance", "tolerance", "violence"
  ],
  phase4: [
    // Original homophones
    "their", "there", "they're", "your", "you're", "its", "it's", "to", "too", "two",
    "whose", "who's", "compliment", "complement", "capitol", "capital", "stationary", "stationery", "principal", "principle",
    "accept", "except", "desert", "dessert", "loose", "lose", "breath", "breathe", "advice", "advise",
    // More homophones
    "affect", "effect", "allowed", "aloud", "altar", "alter", "bare", "bear", "base", "bass",
    "board", "bored", "brake", "break", "buy", "by", "bye", "cell", "sell", "cent",
    "scent", "sent", "cereal", "serial", "coarse", "course", "council", "counsel", "dear", "deer",
    "die", "dye", "fair", "fare", "flour", "flower", "forth", "fourth", "grate", "great",
    "heal", "heel", "hear", "here", "hole", "whole", "hour", "our", "knew", "new",
    "know", "no", "lead", "led", "lessen", "lesson", "made", "maid", "mail", "male",
    "meat", "meet", "minor", "miner", "morning", "mourning", "night", "knight", "one", "won",
    "pail", "pale", "pair", "pear", "peace", "piece", "plain", "plane", "poor", "pour",
    "pray", "prey", "rain", "reign", "read", "reed", "right", "write", "road", "rode",
    "role", "roll", "sail", "sale", "scene", "seen", "sea", "see", "sew", "so",
    "soar", "sore", "some", "sum", "son", "sun", "stair", "stare", "stake", "steak",
    "steal", "steel", "tail", "tale", "threw", "through", "wait", "weight", "waste", "waist",
    "way", "weigh", "weak", "week", "wear", "where", "weather", "whether", "which", "witch"
  ],
  phase5: [
    // Original Greek/Latin roots
    "telephone", "television", "photograph", "biography", "psychology", "automatic", "microscope", "thermometer", "manuscript", "dictionary",
    "interrupt", "transportation", "construction", "submarine", "analysis", "evaluate", "synthesize", "hypothesis", "perspective", "significant",
    "contemporary", "legitimate", "demonstrate", "fundamental", "ecosystem", "democracy", "equation", "civilization", "architecture", "atmosphere",
    // More Greek roots
    "autograph", "automobile", "autonomy", "bibliography", "biology", "chronological", "democracy", "geography", "geology", "geometry",
    "graphic", "hydroelectric", "monologue", "monopoly", "mythology", "paragraph", "perimeter", "philosophy", "photograph", "polygraph",
    "synonym", "technology", "telegram", "telegraph", "telescope", "theology", "thermometer", "asteroid", "astronaut", "astronomy",
    // More Latin roots
    "abbreviate", "accelerate", "accumulate", "accurate", "administration", "advertisement", "agriculture", "anniversary", "anticipate", "appreciate",
    "approximate", "artificial", "beneficial", "calculate", "certificate", "circumstance", "collaborate", "communicate", "concentrate", "congratulate",
    "consequence", "considerable", "constitution", "contribute", "controversy", "cooperation", "correspond", "curiosity", "deliberate", "denominator",
    "determination", "differentiate", "discriminate", "distribute", "elementary", "eliminate", "environment", "equivalent", "exaggerate", "experiment",
    "explanation", "extraordinary", "facilitate", "fortunate", "generation", "government", "graduation", "identification", "illustration", "imagination",
    "immediately", "immigration", "independent", "individual", "information", "ingredient", "inspiration", "institution", "investigation", "laboratory"
  ],
  phase6: [
    // Original literary terms
    "protagonist", "antagonist", "exposition", "foreshadowing", "flashback", "metaphor", "simile", "personification", "alliteration", "onomatopoeia",
    "ferocious", "luminous", "treacherous", "spectacular", "mysterious", "courageous", "melancholy", "exasperated", "triumphant", "ominous",
    "whispered", "exclaimed", "interrupted", "murmured", "declared", "sorcerer", "enchanted", "galaxy", "android", "dimension",
    // More literary terms
    "allegory", "ambiguity", "assonance", "characterization", "climax", "connotation", "denouement", "dialogue", "diction", "epilogue",
    "euphemism", "hyperbole", "imagery", "irony", "juxtaposition", "narrative", "paradox", "perspective", "prologue", "resolution",
    "satire", "soliloquy", "symbolism", "theme", "tone", "tragedy", "archetype", "motif", "oxymoron", "rhetoric",
    // Advanced vocabulary
    "abyss", "aesthetic", "ambiguous", "anonymous", "apocalypse", "catastrophe", "celestial", "chronological", "clandestine", "commemorate",
    "contemporary", "defiant", "dilapidated", "eloquent", "eminence", "ephemeral", "eradicate", "ethereal", "euphoria", "exquisite",
    "formidable", "grotesque", "harmonious", "illuminate", "immaculate", "impeccable", "indigenous", "inevitable", "infinite", "ingenious",
    "insidious", "intricate", "labyrinth", "magnificent", "malevolent", "meticulous", "monumental", "nostalgic", "notorious", "obscure",
    "omniscient", "opulent", "paramount", "peculiar", "perpetual", "phenomenon", "picturesque", "poignant", "precarious", "prestigious",
    "profound", "propaganda", "prosperous", "provocative", "quintessential", "reconnaissance", "redundant", "reminiscent", "resilient", "revolutionary",
    "sanctuary", "scrutinize", "serendipity", "sophisticated", "spontaneous", "substantial", "supernatural", "surveillance", "tumultuous", "ubiquitous"
  ]
};

// Word definitions for spelling games
export const wordDefinitions: Record<string, string> = {
  // Phase 1 - Original
  sprint: "To run at full speed for a short distance",
  strength: "The quality of being physically strong",
  splash: "To cause liquid to scatter in drops",
  shrink: "To become smaller in size",
  prompt: "Done without delay; or a cue to help remember something",
  twelfth: "Coming after eleven others in a series (12th)",
  sketch: "A rough or unfinished drawing",
  flake: "A small, flat, thin piece of something",
  drone: "A remote-controlled flying device; or a continuous humming sound",
  shrine: "A holy or sacred place",
  basket: "A container made of woven material",
  picnic: "An outdoor meal eaten in nature",
  robot: "A machine that can perform tasks automatically",
  compete: "To try to win against others",
  respond: "To reply or answer to something",
  burger: "A sandwich made with a patty of ground meat",
  squirrel: "A small furry animal with a bushy tail that lives in trees",
  explore: "To travel through an unfamiliar area to learn about it",
  emergency: "A serious, unexpected situation requiring immediate action",
  territory: "An area of land belonging to a person, animal, or group",
  // Phase 1 - New consonant blends
  blanket: "A large piece of soft fabric used for warmth",
  branch: "A part of a tree that grows out from the trunk",
  bridge: "A structure built over water or a gap to cross it",
  brother: "A male sibling",
  cluster: "A group of similar things close together",
  crunch: "A crushing or grinding sound; or to chew loudly",
  dragon: "A mythical fire-breathing creature",
  dress: "A piece of clothing worn by women and girls",
  flight: "The act of flying through the air",
  freeze: "To become solid from cold; to stop moving",
  friend: "A person you like and enjoy spending time with",
  glitter: "Tiny pieces of shiny material; to sparkle",
  grass: "Green plants that cover lawns and fields",
  grandpa: "Your grandfather; your parent's father",
  planet: "A large object in space that orbits a star",
  practice: "To do something repeatedly to improve",
  present: "A gift; or the current time; or to show",
  problem: "A difficult situation that needs to be solved",
  program: "A plan of activities; or computer software",
  promise: "A commitment to do or not do something",
  scratch: "To scrape with fingernails or claws",
  screen: "A flat surface for displaying images",
  script: "The written text of a play or movie",
  scream: "To make a loud, high-pitched cry",
  string: "A thin cord or rope",
  stripe: "A long narrow band of color",
  strong: "Having great physical power",
  street: "A road in a city or town",
  stretch: "To extend or pull out to full length",
  straight: "Not curved or bent; direct",
  thread: "A thin strand of cotton or other material",
  throat: "The front part of the neck; passage for food and air",
  throne: "A special chair for a king or queen",
  through: "Moving in one side and out the other",
  thrust: "To push forcefully",
  traffic: "Vehicles moving on roads",
  travel: "To go from one place to another",
  treasure: "Valuable items like gold and jewels",
  tremble: "To shake slightly from fear or cold",
  triangle: "A shape with three sides",
  // Phase 1 - Digraphs
  kitchen: "A room where food is prepared and cooked",
  chicken: "A common farm bird raised for eggs and meat",
  chapter: "A main section of a book",
  children: "Young human beings (plural of child)",
  champion: "A winner of a competition",
  challenge: "A difficult task or contest",
  shadow: "A dark shape made when something blocks light",
  shelter: "A place giving protection from weather or danger",
  whisper: "To speak very quietly",
  whether: "Used to express a choice between alternatives",
  phantom: "A ghost or apparition",
  elephant: "A very large animal with a trunk and tusks",
  dolphin: "An intelligent sea mammal",
  trophy: "An award for winning a competition",
  alphabet: "All the letters of a language in order",
  nephew: "The son of your brother or sister",
  orphan: "A child whose parents have died",
  triumph: "A great victory or achievement",
  sphere: "A round 3D shape like a ball",
  // Phase 1 - R-controlled
  carpet: "A floor covering made of thick fabric",
  harvest: "The time when crops are gathered",
  market: "A place where goods are bought and sold",
  target: "Something aimed at; a goal",
  garden: "An area where plants and flowers are grown",
  partner: "A person who shares in an activity",
  perfect: "Without any flaws or mistakes",
  perhaps: "Maybe; possibly",
  perform: "To carry out an action; to entertain",
  permit: "To allow; or a document giving permission",
  nervous: "Feeling worried or anxious",
  service: "Work done to help others",
  certain: "Sure; without doubt",
  curtain: "A piece of fabric hung at a window",
  surface: "The outside or top layer of something",
  purpose: "The reason for doing something",
  surprise: "An unexpected event; to astonish",
  turnip: "A round white root vegetable",
  turkey: "A large bird often eaten at Thanksgiving",
  turtle: "A reptile with a hard shell",
  
  // Phase 2 - Original
  making: "The process of creating something",
  hoping: "Wanting something to happen or be true",
  creating: "Bringing something into existence",
  usable: "Able to be used; functional",
  running: "Moving quickly on foot",
  biggest: "Largest in size",
  occurred: "Happened or took place",
  traveler: "A person who is on a journey",
  tried: "Made an attempt to do something",
  happiness: "The state of being happy",
  beautiful: "Very pleasing to look at",
  studied: "Devoted time to learning about something",
  foxes: "Wild animals with pointed ears and bushy tails (plural)",
  babies: "Very young children (plural)",
  churches: "Buildings for religious worship (plural)",
  leaves: "Flat green parts of a plant (plural)",
  heroes: "People admired for brave deeds (plural)",
  reefs: "Ridges of rock or coral near water surface (plural)",
  shelves: "Flat boards for holding things (plural)",
  mice: "Small rodents (plural of mouse)",
  disagreement: "A difference of opinion",
  uncomfortable: "Causing or feeling physical or mental discomfort",
  nonexistent: "Not existing or not real",
  overreaction: "A more emotional response than necessary",
  subtraction: "The mathematical operation of taking away",
  intercontinental: "Between or among continents",
  meaningful: "Having purpose or significance",
  fearlessly: "Without any fear; bravely",
  hopelessness: "The feeling that things will not improve",
  // Phase 2 - Drop-e rule
  having: "Possessing or owning",
  giving: "Providing something to someone",
  taking: "Getting hold of something",
  coming: "Moving toward or arriving",
  loving: "Feeling deep affection",
  moving: "Changing position or location",
  proving: "Showing something to be true",
  serving: "Providing food or assistance",
  shaking: "Moving back and forth rapidly",
  skating: "Gliding on ice or wheels",
  trading: "Exchanging goods or services",
  waving: "Moving hand back and forth as greeting",
  baking: "Cooking food in an oven",
  caring: "Feeling concern for others",
  daring: "Brave and willing to take risks",
  facing: "Looking toward; confronting",
  gracing: "Adding beauty or honor to",
  placing: "Putting in a particular position",
  racing: "Competing in speed",
  spacing: "Arranging with gaps between",
  // Phase 2 - Doubling rule
  batting: "Hitting with a bat; or soft material for padding",
  cutting: "Dividing with a sharp tool",
  getting: "Obtaining or receiving",
  hitting: "Striking with force",
  letting: "Allowing or permitting",
  putting: "Placing in a position",
  setting: "Placing or arranging",
  sitting: "Resting in a seated position",
  stopping: "Ceasing to move or act",
  swimming: "Moving through water",
  beginning: "The start of something",
  forgetting: "Failing to remember",
  occurring: "Taking place; happening",
  planning: "Making arrangements for the future",
  preferring: "Liking one thing more than another",
  referring: "Mentioning or directing attention to",
  regretting: "Feeling sorry about something",
  submitting: "Presenting for consideration",
  winning: "Being victorious",
  wrapping: "Covering with paper or material",
  // Phase 2 - Y to I
  carried: "Transported from one place to another",
  copied: "Made a duplicate of",
  cried: "Shed tears; wept",
  dried: "Removed moisture from",
  emptied: "Removed all contents from",
  fried: "Cooked in hot oil or fat",
  hurried: "Moved or acted quickly",
  married: "United in marriage",
  replied: "Responded to a question",
  worried: "Felt anxious or troubled",
  busiest: "Most occupied or active",
  earliest: "Happening first in time",
  easiest: "Requiring the least effort",
  funniest: "Most amusing or comical",
  happiest: "Feeling the most joy",
  heaviest: "Having the most weight",
  laziest: "Least willing to work",
  luckiest: "Having the most good fortune",
  prettiest: "Most attractive or beautiful",
  ugliest: "Most unpleasant to look at",
  // Phase 2 - Plurals
  calves: "Young cows (plural of calf)",
  halves: "Two equal parts (plural of half)",
  knives: "Cutting tools with blades (plural of knife)",
  lives: "The state of being alive (plural of life)",
  loaves: "Shaped pieces of bread (plural of loaf)",
  scarves: "Pieces of fabric worn around the neck (plural of scarf)",
  thieves: "People who steal (plural of thief)",
  wives: "Married women (plural of wife)",
  wolves: "Wild dog-like animals (plural of wolf)",
  yourselves: "You, when referring to more than one person",
  potatoes: "Starchy vegetables grown underground",
  tomatoes: "Red fruits often used in cooking",
  echoes: "Sounds that bounce back (plural of echo)",
  mosquitoes: "Small flying insects that bite",
  tornadoes: "Violent spinning windstorms",
  volcanoes: "Mountains that can erupt with lava",
  buffaloes: "Large wild cattle",
  dominoes: "Small rectangular game pieces",
  mangoes: "Sweet tropical fruits",
  zeroes: "The number 0 (plural of zero)",
  
  // Phase 3 - Original
  knowledge: "Facts, information, and skills acquired through experience or education",
  wrestle: "To struggle or fight with someone by grappling",
  gnome: "A small mythical creature that lives underground",
  psychology: "The study of the mind and behavior",
  solemn: "Serious and without humor",
  salmon: "A large fish with pink flesh",
  receipt: "A written record that something was received or paid for",
  scissors: "A cutting tool with two blades",
  mortgage: "A loan used to buy property",
  handsome: "Good-looking (often used for men)",
  necessary: "Required; needed",
  recommend: "To suggest as good or suitable",
  occasion: "A special event or time",
  restaurant: "A place where meals are served to customers",
  accommodate: "To provide space or lodging for",
  calendar: "A chart showing days, weeks, and months of a year",
  colonel: "A military officer rank",
  rhythm: "A regular repeated pattern of sound or movement",
  Wednesday: "The day of the week between Tuesday and Thursday",
  Arctic: "The region around the North Pole",
  receive: "To get or be given something",
  believe: "To accept as true",
  weird: "Strange or unusual",
  neighbor: "A person living next door or nearby",
  ceiling: "The upper surface of a room",
  achieve: "To successfully reach a goal",
  seizure: "A sudden attack or the act of taking by force",
  freight: "Goods transported by truck, train, ship, or aircraft",
  // Phase 3 - Silent letters
  knight: "A medieval soldier who served a lord",
  knuckle: "A finger joint",
  knife: "A tool with a sharp blade for cutting",
  knock: "To hit a door to get attention",
  knot: "A fastening made by tying",
  kneel: "To go down on your knees",
  written: "Expressed in writing",
  wrapper: "A covering or packaging material",
  wrinkle: "A small crease or fold in skin or fabric",
  wrist: "The joint connecting hand to arm",
  gnarled: "Twisted and knotty",
  gnaw: "To bite or chew persistently",
  design: "A plan or drawing; to create",
  resign: "To quit a job or position",
  campaign: "An organized effort for a goal",
  foreign: "From another country",
  reign: "The period a ruler is in power",
  sovereign: "A supreme ruler; independent",
  assign: "To give a task or responsibility",
  consign: "To hand over or deliver",
  doubt: "Uncertainty about something",
  debt: "Money owed to another",
  subtle: "Delicate; not obvious",
  plumber: "A person who fixes pipes",
  thumb: "The short thick finger on the hand",
  climb: "To go up using hands and feet",
  comb: "A tool for styling hair",
  crumb: "A tiny piece of bread or cake",
  dumb: "Unable to speak; or foolish (informal)",
  lamb: "A young sheep",
  aisle: "A passage between rows of seats",
  island: "Land surrounded by water",
  isle: "A small island",
  debris: "Scattered pieces of rubbish",
  chassis: "The base frame of a vehicle",
  corps: "A group of people working together",
  depot: "A storage place or station",
  rapport: "A friendly relationship",
  rendezvous: "A planned meeting place",
  ballet: "A graceful style of dance",
  // Phase 3 - I before E
  belief: "Trust or confidence in something",
  brief: "Short in duration",
  chief: "A leader or head person",
  field: "An open area of land",
  grief: "Deep sorrow",
  piece: "A part of something",
  relief: "A feeling of comfort after worry",
  shield: "Protection; a piece of armor",
  thief: "Someone who steals",
  yield: "To produce; or to give way",
  fierce: "Violent or aggressive",
  pierce: "To make a hole through",
  frontier: "The edge of settled land",
  efficient: "Working well without waste",
  sufficient: "Enough; adequate",
  ancient: "Very old; from long ago",
  patient: "Able to wait calmly; or a person receiving medical care",
  science: "The study of the natural world",
  conscience: "Inner sense of right and wrong",
  // Phase 3 - Tricky words
  absence: "Being away or not present",
  abundance: "A very large quantity",
  acquaintance: "A person you know slightly",
  appearance: "How something looks",
  assistance: "Help or support",
  attendance: "Being present somewhere",
  excellence: "The quality of being outstanding",
  existence: "The state of being real",
  independence: "Freedom from control",
  intelligence: "The ability to learn and understand",
  maintenance: "Keeping something in good condition",
  performance: "An act of presenting something",
  perseverance: "Continuing despite difficulty",
  preference: "A greater liking for one thing",
  presence: "Being in a place",
  reference: "A mention or source of information",
  resistance: "Refusing to accept something",
  significance: "The importance of something",
  tolerance: "Accepting differences",
  violence: "Physical force intended to hurt",
  
  // Phase 4 - Original homophones
  their: "Belonging to them",
  there: "In or at that place",
  "they're": "Short for 'they are'",
  your: "Belonging to you",
  "you're": "Short for 'you are'",
  its: "Belonging to it",
  "it's": "Short for 'it is' or 'it has'",
  to: "Expressing direction toward a place",
  too: "Also; or to an excessive degree",
  two: "The number 2",
  whose: "Belonging to which person",
  "who's": "Short for 'who is' or 'who has'",
  compliment: "A polite expression of praise",
  complement: "Something that completes or goes well with something else",
  capitol: "A building where a legislature meets",
  capital: "The main city of a country or state; or wealth/money",
  stationary: "Not moving; still",
  stationery: "Writing materials like paper and envelopes",
  principal: "The head of a school; or most important",
  principle: "A fundamental truth or rule",
  accept: "To receive willingly",
  except: "Not including; other than",
  desert: "A dry, sandy region; or to abandon",
  dessert: "A sweet dish eaten after a meal",
  loose: "Not tight; not firmly fixed",
  lose: "To be unable to find; to fail to win",
  breath: "Air taken into or out of the lungs (noun)",
  breathe: "To take air into the lungs (verb)",
  advice: "Guidance or recommendations (noun)",
  advise: "To give guidance or recommendations (verb)",
  // Phase 4 - More homophones
  affect: "To influence or change (verb)",
  effect: "A result or outcome (noun)",
  allowed: "Permitted to do something",
  aloud: "In a voice that can be heard",
  altar: "A table for religious ceremonies",
  alter: "To change or modify",
  bare: "Without covering; naked",
  bear: "A large furry animal; or to carry",
  base: "The bottom or foundation",
  bass: "A low sound; or a type of fish",
  board: "A flat piece of wood",
  bored: "Feeling uninterested",
  brake: "A device to stop movement",
  break: "To separate into pieces",
  buy: "To purchase with money",
  by: "Near or beside",
  bye: "Short for goodbye",
  cell: "A small room; or basic unit of life",
  sell: "To exchange for money",
  cent: "A unit of money (1/100 of a dollar)",
  scent: "A smell or fragrance",
  sent: "Past tense of send",
  cereal: "Grain-based breakfast food",
  serial: "Happening in a series",
  coarse: "Rough in texture",
  course: "A path or direction; or a class",
  council: "A group that makes decisions",
  counsel: "Advice; or a lawyer",
  dear: "Beloved; or expensive",
  deer: "A forest animal with antlers",
  die: "To stop living",
  dye: "A coloring substance",
  fair: "Just and honest; or a carnival",
  fare: "The cost of travel",
  flour: "Powder made from grain for baking",
  flower: "The bloom of a plant",
  forth: "Forward; onward",
  fourth: "Coming after third (4th)",
  grate: "To shred into pieces; or a metal frame",
  great: "Very large or excellent",
  heal: "To make healthy again",
  heel: "The back part of the foot",
  hear: "To perceive sound",
  here: "In this place",
  hole: "An opening or gap",
  whole: "Complete; entire",
  hour: "Sixty minutes",
  our: "Belonging to us",
  knew: "Past tense of know",
  new: "Recently made; not old",
  know: "To have information about",
  no: "The opposite of yes",
  lead: "A heavy metal; or to guide",
  led: "Past tense of lead (to guide)",
  lessen: "To make smaller or less",
  lesson: "Something taught or learned",
  made: "Created or produced",
  maid: "A female servant",
  mail: "Letters and packages delivered",
  male: "A boy or man",
  meat: "Animal flesh used as food",
  meet: "To come together with someone",
  minor: "Small or unimportant; or underage",
  miner: "A person who works in a mine",
  morning: "The early part of the day",
  mourning: "Feeling sad after a death",
  night: "The time when it is dark",
  one: "The number 1",
  won: "Past tense of win",
  pail: "A bucket",
  pale: "Light in color; or looking sick",
  pair: "A set of two",
  pear: "A green or yellow fruit",
  peace: "Freedom from war; calm",
  plain: "Simple; or a flat area of land",
  plane: "An aircraft; or a flat surface",
  poor: "Having little money",
  pour: "To make liquid flow",
  pray: "To speak to God",
  prey: "An animal hunted by another",
  rain: "Water falling from clouds",
  read: "To look at and understand written words",
  reed: "A tall grass that grows in water",
  right: "Correct; or the opposite of left",
  write: "To form letters or words",
  road: "A path for vehicles",
  rode: "Past tense of ride",
  role: "A part played by an actor; or function",
  roll: "To turn over; or a small bread",
  sail: "A sheet that catches wind on a boat",
  sale: "Selling at reduced prices",
  scene: "A place where action occurs",
  seen: "Past participle of see",
  sea: "A large body of salt water",
  see: "To perceive with eyes",
  sew: "To join fabric with needle and thread",
  so: "Therefore; or to such a degree",
  soar: "To fly high in the sky",
  sore: "Painful; or an injured spot",
  some: "An unspecified amount",
  sum: "A total; the result of addition",
  son: "A male child",
  sun: "The star at the center of our solar system",
  stair: "A step in a staircase",
  stare: "To look fixedly at something",
  stake: "A pointed wooden post; or a risk",
  steak: "A slice of meat or fish",
  steal: "To take without permission",
  steel: "A strong metal alloy",
  tail: "The rear part of an animal",
  tale: "A story",
  threw: "Past tense of throw",
  wait: "To stay in place expecting something",
  weight: "How heavy something is",
  waste: "To use carelessly; or garbage",
  waist: "The middle part of the body",
  way: "A path or method",
  weigh: "To measure how heavy",
  weak: "Lacking strength",
  week: "Seven days",
  wear: "To have clothing on",
  where: "In what place",
  weather: "Atmospheric conditions like rain or sun",
  which: "What one (of choices)",
  witch: "A person who practices magic",
  
  // Phase 5 - Original
  telephone: "A device for speaking with someone at a distance",
  television: "An electronic device for watching shows and movies",
  photograph: "A picture made using a camera",
  biography: "A written account of someone's life",
  automatic: "Working by itself with little or no human control",
  microscope: "An instrument for viewing very small objects",
  thermometer: "An instrument for measuring temperature",
  manuscript: "A handwritten or typed document, especially before printing",
  dictionary: "A book listing words and their meanings",
  interrupt: "To stop someone while they are speaking or doing something",
  transportation: "The movement of people or goods from one place to another",
  construction: "The process of building something",
  submarine: "A watercraft that can operate underwater",
  analysis: "Detailed examination of something",
  evaluate: "To judge the value or quality of something",
  synthesize: "To combine different ideas into a connected whole",
  hypothesis: "A proposed explanation for something",
  perspective: "A particular way of viewing things",
  significant: "Important; meaningful",
  contemporary: "Belonging to the present time; modern",
  legitimate: "Lawful; conforming to rules",
  demonstrate: "To show clearly; to prove",
  fundamental: "Basic; essential",
  ecosystem: "A community of living things and their environment",
  democracy: "A system of government by the people",
  equation: "A mathematical statement showing two things are equal",
  civilization: "An advanced stage of human society",
  architecture: "The design and construction of buildings",
  atmosphere: "The layer of gases surrounding Earth; or the mood of a place",
  // Phase 5 - Greek roots
  autograph: "A person's signature",
  automobile: "A car; a self-moving vehicle",
  autonomy: "Self-governance; independence",
  bibliography: "A list of books and sources",
  biology: "The study of living things",
  chronological: "Arranged in time order",
  geography: "The study of Earth's surface",
  geology: "The study of rocks and Earth's structure",
  geometry: "The math of shapes and space",
  graphic: "Relating to visual art or images",
  hydroelectric: "Electricity produced from water power",
  monologue: "A long speech by one person",
  monopoly: "Exclusive control over something",
  mythology: "A collection of myths and legends",
  paragraph: "A section of writing",
  perimeter: "The outer boundary of a shape",
  philosophy: "The study of knowledge and existence",
  polygraph: "A lie detector machine",
  synonym: "A word with the same meaning as another",
  technology: "The use of science for practical purposes",
  telegram: "A message sent by telegraph",
  telegraph: "A system for sending messages over wires",
  telescope: "An instrument for viewing distant objects",
  theology: "The study of religion and God",
  asteroid: "A rocky object orbiting the sun",
  astronaut: "A person trained to travel in space",
  astronomy: "The study of stars and planets",
  // Phase 5 - Latin roots
  abbreviate: "To shorten a word or phrase",
  accelerate: "To speed up",
  accumulate: "To gather or collect over time",
  accurate: "Correct and without errors",
  administration: "The management of an organization",
  advertisement: "A public notice promoting something",
  agriculture: "Farming; growing crops and raising animals",
  anniversary: "A yearly celebration of an event",
  anticipate: "To expect or look forward to",
  appreciate: "To value highly; to be grateful for",
  approximate: "Close to the actual; nearly correct",
  artificial: "Made by humans; not natural",
  beneficial: "Producing good results; helpful",
  calculate: "To figure out using math",
  certificate: "An official document proving something",
  circumstance: "A condition or situation",
  collaborate: "To work together with others",
  communicate: "To share information with others",
  concentrate: "To focus attention; or to make stronger",
  congratulate: "To express praise for an achievement",
  consequence: "A result or effect of an action",
  considerable: "Large in size or amount",
  constitution: "A system of fundamental laws",
  contribute: "To give or add to something",
  controversy: "A public disagreement",
  cooperation: "Working together for a common goal",
  correspond: "To communicate by letters; to match",
  curiosity: "A strong desire to know something",
  deliberate: "Done on purpose; or to consider carefully",
  denominator: "The bottom number in a fraction",
  determination: "Firmness of purpose; willpower",
  differentiate: "To recognize differences between",
  discriminate: "To treat unfairly; or to distinguish",
  distribute: "To give out to many",
  elementary: "Basic; relating to early education",
  eliminate: "To remove or get rid of",
  environment: "The surroundings; nature",
  equivalent: "Equal in value or meaning",
  exaggerate: "To overstate or stretch the truth",
  experiment: "A test to discover something",
  explanation: "A statement that makes something clear",
  extraordinary: "Very unusual or remarkable",
  facilitate: "To make easier",
  fortunate: "Lucky; having good fortune",
  generation: "People born around the same time",
  government: "The system that rules a country",
  graduation: "The completion of a course of study",
  identification: "Proof of who someone is",
  illustration: "A picture that explains something",
  imagination: "The ability to create mental images",
  immediately: "Right now; without delay",
  immigration: "Moving to a new country to live",
  independent: "Free from control; self-reliant",
  individual: "A single person or thing",
  information: "Facts or knowledge about something",
  ingredient: "A component of a mixture",
  inspiration: "Something that motivates creativity",
  institution: "An established organization",
  investigation: "A careful search for facts",
  laboratory: "A room for scientific experiments",
  
  // Phase 6 - Original
  protagonist: "The main character in a story",
  antagonist: "A character who opposes the main character",
  exposition: "The introduction of background information in a story",
  foreshadowing: "A hint of what will happen later in a story",
  flashback: "A scene showing events from the past",
  metaphor: "A comparison saying something IS something else",
  simile: "A comparison using 'like' or 'as'",
  personification: "Giving human qualities to non-human things",
  alliteration: "The repetition of the same sound at the start of words",
  onomatopoeia: "A word that sounds like what it describes (buzz, splash)",
  ferocious: "Extremely fierce or violent",
  luminous: "Full of light; glowing",
  treacherous: "Dangerous and unpredictable",
  spectacular: "Impressively beautiful or dramatic",
  mysterious: "Difficult to understand or explain",
  courageous: "Brave; not afraid of danger",
  melancholy: "A feeling of deep sadness",
  exasperated: "Intensely irritated and frustrated",
  triumphant: "Feeling or showing great joy after a victory",
  ominous: "Giving the impression that something bad will happen",
  whispered: "Spoke very quietly",
  exclaimed: "Cried out suddenly in surprise or emotion",
  interrupted: "Stopped someone while they were speaking",
  murmured: "Said something in a soft, quiet voice",
  declared: "Announced something formally",
  sorcerer: "A person who practices magic",
  enchanted: "Under a magic spell; or delighted",
  galaxy: "A huge system of stars in space",
  android: "A robot with a human appearance",
  dimension: "A measurable extent (length, width, height); or a realm",
  // Phase 6 - Literary terms
  allegory: "A story with a hidden meaning",
  ambiguity: "Having more than one possible meaning",
  assonance: "Repetition of vowel sounds in words",
  characterization: "How an author develops characters",
  climax: "The most exciting point in a story",
  connotation: "The feelings a word suggests beyond its meaning",
  denouement: "The final outcome of a story",
  dialogue: "Conversation between characters",
  diction: "Word choice in writing or speech",
  epilogue: "A section at the end of a book",
  euphemism: "A mild word used instead of an offensive one",
  hyperbole: "Extreme exaggeration for effect",
  imagery: "Descriptive language that creates pictures",
  irony: "When the opposite of what's expected happens",
  juxtaposition: "Placing things side by side for contrast",
  narrative: "A story or account of events",
  paradox: "A statement that seems contradictory but is true",
  prologue: "An introduction to a story",
  resolution: "How a problem is solved in a story",
  satire: "Using humor to criticize something",
  soliloquy: "A speech by a character alone on stage",
  symbolism: "Using objects to represent ideas",
  theme: "The main idea or message of a story",
  tone: "The author's attitude toward the subject",
  tragedy: "A story with an unhappy ending",
  archetype: "A typical example of a character or situation",
  motif: "A recurring element in a story",
  oxymoron: "Two opposite words used together",
  rhetoric: "The art of persuasive speaking or writing",
  // Phase 6 - Advanced vocabulary
  abyss: "A deep bottomless pit",
  aesthetic: "Relating to beauty and art",
  ambiguous: "Having more than one meaning",
  anonymous: "Without a known name",
  apocalypse: "A catastrophic disaster; end of the world",
  catastrophe: "A sudden disaster",
  celestial: "Relating to the sky or heavens",
  clandestine: "Done in secret",
  commemorate: "To honor the memory of",
  defiant: "Boldly resistant or challenging",
  dilapidated: "Falling apart; in poor condition",
  eloquent: "Fluent and persuasive in speaking",
  eminence: "Fame or high standing",
  ephemeral: "Lasting only a short time",
  eradicate: "To destroy completely",
  ethereal: "Extremely delicate; heavenly",
  euphoria: "A feeling of intense happiness",
  exquisite: "Extremely beautiful and delicate",
  formidable: "Inspiring fear or respect",
  grotesque: "Ugly or distorted in appearance",
  harmonious: "Pleasingly combined; peaceful",
  illuminate: "To light up; to explain clearly",
  immaculate: "Perfectly clean; spotless",
  impeccable: "Flawless; without errors",
  indigenous: "Native to a particular place",
  inevitable: "Certain to happen; unavoidable",
  infinite: "Without limits; endless",
  ingenious: "Clever and inventive",
  insidious: "Gradually harmful; treacherous",
  intricate: "Very complicated with many details",
  labyrinth: "A complex maze",
  magnificent: "Extremely beautiful or impressive",
  malevolent: "Having evil intentions",
  meticulous: "Showing great attention to detail",
  monumental: "Great in importance or size",
  nostalgic: "Longing for the past",
  notorious: "Famous for something bad",
  obscure: "Not well known; unclear",
  omniscient: "Knowing everything",
  opulent: "Luxurious and wealthy",
  paramount: "Of supreme importance",
  peculiar: "Strange or unusual",
  perpetual: "Never ending; continuous",
  phenomenon: "A remarkable event or fact",
  picturesque: "Visually attractive; charming",
  poignant: "Evoking a keen sense of sadness",
  precarious: "Dangerously unstable",
  prestigious: "Having high status and respect",
  profound: "Very deep; intensely felt",
  propaganda: "Information used to promote a cause",
  prosperous: "Successful and wealthy",
  provocative: "Causing strong reactions",
  quintessential: "The perfect example of something",
  reconnaissance: "Military observation of an area",
  redundant: "No longer needed; repetitive",
  reminiscent: "Suggesting memories of something",
  resilient: "Able to recover quickly",
  revolutionary: "Involving dramatic change",
  sanctuary: "A safe place; a holy place",
  scrutinize: "To examine closely",
  serendipity: "Finding good things by chance",
  sophisticated: "Complex; cultured and worldly",
  spontaneous: "Happening without planning",
  substantial: "Large in amount or size",
  supernatural: "Beyond natural explanation",
  surveillance: "Close observation of someone",
  tumultuous: "Loud and chaotic",
  ubiquitous: "Found everywhere"
};

export const resources = [
  { category: "foundational_phonics", items: [
    { title: "OnTrack Reading Middle School Phonics Course", description: "A mini-curriculum for middle schoolers to improve decoding of multisyllable words.", qualityRating: 4, difficultyLevel: "intermediate", timeCommitment: "10 sessions of 15 minutes", cost: "Paid (approx. $20)", url: "https://www.ontrackreading.com/phonics-program/middle-school-phonics-course", bestForPhase: "Foundational Phonics" },
    { title: "Reading Horizons", description: "Software program for reading and phonics skills development.", qualityRating: 4, difficultyLevel: "intermediate", timeCommitment: "Varies (self-paced)", cost: "Paid (with free trial)", url: "https://www.readinghorizons.com/", bestForPhase: "Foundational Phonics" },
    { title: "Phonics.com", description: "Free online platform with phonics resources, activities, and games.", qualityRating: 3, difficultyLevel: "beginner", timeCommitment: "Varies (self-paced)", cost: "Free", url: "https://www.phonics.com/", bestForPhase: "Foundational Phonics" }
  ]},
  { category: "spelling_rules_and_patterns", items: [
    { title: "Spelling-Words-Well.com", description: "Spelling resources for 6th grade including word lists, games, worksheets.", qualityRating: 4, difficultyLevel: "intermediate", timeCommitment: "Varies (self-paced)", cost: "Free", url: "https://www.spelling-words-well.com/6th-grade-spelling.html", bestForPhase: "Spelling Rules and Patterns" },
    { title: "Spelling Stars", description: "Interactive games, tests, and customizable spelling lists for 6th grade.", qualityRating: 4, difficultyLevel: "intermediate", timeCommitment: "Varies (self-paced)", cost: "Paid (with free trial)", url: "https://www.spellingstars.com/6th-grade", bestForPhase: "Spelling Rules and Patterns" },
    { title: "All About Spelling", description: "Comprehensive, multisensory spelling program based on Orton-Gillingham approach.", qualityRating: 5, difficultyLevel: "beginner to advanced", timeCommitment: "20 minutes per day", cost: "Paid (approx. $50-65 per level)", url: "https://www.allaboutlearningpress.com/all-about-spelling/", bestForPhase: "Spelling Rules and Patterns" }
  ]},
  { category: "vocabulary_building", items: [
    { title: "Vocabulary.com", description: "Interactive platform for learning new words through games and quizzes.", qualityRating: 5, difficultyLevel: "intermediate to advanced", timeCommitment: "Varies (self-paced)", cost: "Free and paid plans", url: "https://www.vocabulary.com/", bestForPhase: "Vocabulary Building" },
    { title: "Membean", description: "Personalized vocabulary learning using cognitive science for long-term retention.", qualityRating: 5, difficultyLevel: "intermediate to advanced", timeCommitment: "Varies (self-paced)", cost: "Paid", url: "https://membean.com/", bestForPhase: "Vocabulary Building" },
    { title: "Knoword", description: "Engaging vocabulary games and custom flashcards.", qualityRating: 4, difficultyLevel: "beginner to intermediate", timeCommitment: "Varies (self-paced)", cost: "Free and paid plans", url: "https://knoword.com/", bestForPhase: "Vocabulary Building" }
  ]},
  { category: "creative_writing", items: [
    { title: "Night Zookeeper", description: "Gamified language arts program encouraging creative writing through interactive lessons.", qualityRating: 5, difficultyLevel: "beginner to intermediate", timeCommitment: "Varies (self-paced)", cost: "Paid (with free trial)", url: "https://www.nightzookeeper.com/", bestForPhase: "Creative Writing" },
    { title: "Storybird", description: "Platform to create and publish storybooks using professional illustrations.", qualityRating: 4, difficultyLevel: "beginner to intermediate", timeCommitment: "Varies (self-paced)", cost: "Free and paid plans", url: "https://storybird.com/", bestForPhase: "Creative Writing" },
    { title: "BoomWriter", description: "Collaborative writing platform using gamification to engage students.", qualityRating: 4, difficultyLevel: "intermediate", timeCommitment: "Varies (self-paced)", cost: "Paid", url: "https://www.boomwriter.com/", bestForPhase: "Creative Writing" }
  ]},
  { category: "gamified_learning", items: [
    { title: "Spelling Shed", description: "Gamified spelling app with competitive leagues and rewards.", qualityRating: 4, difficultyLevel: "beginner to intermediate", timeCommitment: "Varies (self-paced)", cost: "Paid", url: "https://www.spellingshed.com/", bestForPhase: "Gamified Learning" },
    { title: "SpellingCity", description: "Vocabulary and spelling practice through fun games and activities.", qualityRating: 4, difficultyLevel: "intermediate to advanced", timeCommitment: "Varies (self-paced)", cost: "Free with premium options", url: "https://www.spellingcity.com/", bestForPhase: "Gamified Learning" }
  ]}
];
